//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IT_FairEntities : DbContext
    {
        public IT_FairEntities()
            : base("name=IT_FairEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Antonimo> Antonimo { get; set; }
        public virtual DbSet<Ejemplo> Ejemplo { get; set; }
        public virtual DbSet<Palabra> Palabra { get; set; }
        public virtual DbSet<Sinonimo> Sinonimo { get; set; }
        public virtual DbSet<TipoPalabra> TipoPalabra { get; set; }
    }
}
